#!/usr/bin/env bash
# configure web-02 server to be identical to web-01 server
apt-get -y update
apt-get -y install nginx
echo "Holberton School second server" > /var/www/html/index.nginx-debian.html
HTTP_H="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"
sed -i "s/server_name _;/$HTTP_H/" /etc/nginx/sites-available/default
service nginx restart
