#!/usr/bin/env bash
# MySQL backup - generates a MySQL dump and creates a compressed archive of it.
mysqldump -u root -p"$1" --all-databases --opt  > backup.sql
tar -czvf "$(date +%d-%m-%Y)".tar.gz backup-sql
