#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1
while [ $i -le 9 ]
do
    if [ $i -eq 9 ]
    then
	printf "Hi\n"
    fi
    printf "Holberton School\n"
    i=$((i + 1))
done
