#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 644 nginx.conf
chown nginx nginx.conf
chgrp nginx nginx.conf
pkill -9 apache2
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
